### PR TITLE
Port Scanner

### PR DESCRIPTION
**Pull request by RiberoD07**
script that checks for open ports given an ip address

### CODE REVIEW

**Comment by RiberoD07** [comment]
pull request in response to #5

**Review by amitsagtani97 — CHANGES_REQUESTED** [review]
@RiberoD07 Hi! can you please create a new directory for your project and include a README file :)

**Comment by RiberoD07** [comment]
made changes as requested

**Comment by amitsagtani97** [comment]
@RiberoD07 Thanks for the PR. :+1:

**Pull request merged**
