### PR TITLE
Add caesar cipher script

### PR DESCRIPTION
**Pull request by jackmcbride**
Short script for breaking caesar cipher challenges. Fun for CTF!

### CODE REVIEW

**Review by amitsagtani97 — CHANGES_REQUESTED** [review]
@jackmcbride Hi! Can you please add a README file with little info about Caesar cipher.

**Comment by jackmcbride** [comment]
Sure thing!

**Comment by jackmcbride** [comment]
Changes implemented.

**Comment by amitsagtani97** [comment]
@jackmcbride thanks for the PR. :+1:

**Pull request merged**
